version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - custom_network
    depends_on:
      - backend
      
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - custom_network
    volumes:
      - ./backend/count.txt:/app/count.txt   

networks:
  custom_network:
    driver: bridge